import Head from 'next/head'
import {BsFillMoonStarsFill, BsSunFill} from 'react-icons/bs'
import {AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube} from 'react-icons/ai';
import Image from "next/image";
import deved from '../public/dev-ed-wave.png';
import design from '../public/design.png';
import code from '../public/code.png';
import consulting from '../public/consulting.png'
import web1 from '../public/web1.png';
import web2 from '../public/web2.png';
import web3 from '../public/web3.png';
import web4 from '../public/web4.png';
import web5 from '../public/web5.png';
import web6 from '../public/web6.png';
import { useState } from 'react';


export default function Home() {
  const [darkMode, setDarkMode] = useState(true);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Kyle Williams Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px-40 xl:px-70 dark:bg-gray-900'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons dark:text-white md:text-2xl lg:text-3xl'>Kyle Williams Portoflio</h1>
              <ul className='flex items-center'>
                <li>
                  {darkMode ? <BsSunFill fill='white' onClick={() => {setDarkMode(!darkMode)}} className='cursor-pointer'/> :
                  <BsFillMoonStarsFill onClick={() => {setDarkMode(!darkMode)}} className='cursor-pointer'/>}
                </li>
                <li><a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href="https://docs.google.com/document/d/1RtP1l5T5Fw3P4W_toDAJsS7LW-8LJgYcJXJ_Mvk5uto/edit?usp=sharing">Resume</a></li>
              </ul>
          </nav>
          <div className='text-center p-8'>
            <h2 className='text-5xl text-teal-600 font-medium md:text-6xl'>Kyle Williams</h2>
            <h3 className='text-2xl py-2 md:text-3xl dark:text-white'>Software Engineer</h3>
            <p className='py-5 mx-auto text-md leading-8 text-gray-800 md:text-xl max-w-xl dark:text-gray-100'>As a software engineer, I am incredibly motivated to implement and integrate software solutions
               that enable products to impact users in new, and innovative ways.</p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-300'>
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillYoutube />
          </div>
          <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96'>
            <Image src={deved} layout='fill' objectFit='cover'/>
          </div>
        </section>

        <section>
          <div className='py-20'>
            <h3 className='text-3xl py-1 dark:text-white'>My skillset</h3>
            <p className='py-2 text-md leading-8 text-gray-800 dark:text-gray-100'>Since the beginning of my journey as a freelance design developer, 
              I've done remote work for many different <span className='text-teal-500'>companies</span>. This included consulting for and collaborating with talented people
              to create business solutions.</p>
              <p className='py-2 text-md leading-8 text-gray-800 dark:text-gray-100'>My prfficiency in Java, JavaScript, HTML, CSS and React
               can be seen in my projects below.</p>
          </div>
          <div className='lg:flex gap-10'>
            <div className='text-center shadow-lg p-10 my-10'>
              <Image src={design} width={100} height={100} />
              <h3 className='text-lg font-medium pt-8 pb-2 dark:text-white'>Beautiful Designs</h3>
              <p className='py-2 dark:text-white'>Creating elegant designs suited for your needs design theory.</p>
              <h4 className='py-4 text-teal-600'>Design tools I use</h4>
              <p className='text-grey-800 py-1 dark:text-white'>Photoshop</p>
              <p className='text-grey-800 py-1 dark:text-white'>Illustrator</p>
              <p className='text-grey-800 py-1 dark:text-white'>Figma</p>
            </div>
            <div className='text-center shadow-lg p-10 my-10 dark:text-white'>
              <Image src={code} width={100} height={100} />
              <h3 className='text-lg font-medium pt-8 pb-2'>Clean Code</h3>
              <p className='py-2'>Clean code built for future engineers.</p>
              <h4 className='py-4 text-teal-600'>Coding tech I use</h4>
              <p className='text-grey-800 py-1'>ReactJS - HTML - JavaScript - Typescript</p>
              <p className='text-grey-800 py-1'>Java - JavaFX</p>
              <p className='text-grey-800 py-1'>SQL - MySQL - SQLite</p>
            </div>
            <div className='text-center shadow-lg p-10 my-10 dark:text-white'>
              <Image src={consulting} width={100} height={100} />
              <h3 className='text-lg font-medium pt-8 pb-2'>Consulting Services</h3>
              <p className='py-2'>Optimizing business processes through expert knowledge.</p>
              <h4 className='py-4 text-teal-600'>Communication tools I use</h4>
              <p className='text-grey-800 py-1'>MS Word</p>
              <p className='text-grey-800 py-1'>MS PowerPoint</p>
              <p className='text-grey-800 py-1'>MS Excel</p>
            </div>
          </div>
        </section>
        <section>
          <div className='py-20 dark:text-white'>
            <h3 className='text-3xl py-1'>Portfolio</h3>
            <p className='py-2 text-md leading-8 text-gray-800 dark:text-white'>Since the beginning of my journey as a freelance design developer, 
              I've done remote work for many different <span className='text-teal-500'>companies</span>. This included consulting for and collaborating with talented people
              to create business solutions.</p>
              <p className='py-2 text-md leading-8 text-gray-800 dark:text-white'>My prfficiency in Java, JavaScript, HTML, CSS and React
               can be seen in my projects below.</p>
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className='basis-1/3 flex-1'><Image src={web1} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout="responsive"/></div>
            <div className='basis-1/3 flex-1'><Image src={web2} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout="responsive"/></div>
            <div className='basis-1/3 flex-1'><Image src={web3} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout="responsive"/></div>
            <div className='basis-1/3 flex-1'><Image src={web4} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout="responsive"/></div>
            <div className='basis-1/3 flex-1'><Image src={web5} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout="responsive"/></div>
            <div className='basis-1/3 flex-1'><Image src={web6} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout="responsive"/></div>
          </div>
        </section>
      </main>
    </div>
  )
}
